### ISSUE TITLE
Super excited to try new version but... 

### ISSUE THREAD

**Issue by Skrell** [young-developer/nppNavigateTo#27]
I immediately hit an issue whereby the plugin doesn't even see all the tabs I have open to search through? 
![image](https://user-images.githubusercontent.com/590266/204320529-88930bc2-aa81-4d92-b10e-a2d11d144f1b.png)
 v8.4.6 32bit

**Comment by young-developer** [comment]
Just tested on 8.4.7(x32) and it looks good. Can you provide more details on layout? Primary and Second view?
![image](https://user-images.githubusercontent.com/4460168/204329392-f6bea708-8a71-48f9-8cc9-79d5fa0779f8.png)

**Comment by Skrell** [comment]
Note that I'm using a portable install of NPP and allow my plugins to be loaded from the install directory instead of app data (ie. I have a allowAppDataPlugins.xml defined)
Is it possible it is an issue bc of this way of using NPP? Also I updated to 8.4.7 so I have the same version you're testing.  The result was identical.

**Comment by Skrell** [comment]
You appear to be correct, when I moved all the files to the primary view it started working; however, now I get this: 
![image](https://user-images.githubusercontent.com/590266/204335074-9bbc9c35-2777-4b02-8c79-f0ffe16ef1b4.png)

**Comment by young-developer** [comment]
@Skrell try this version I fixed some buffer loading issues: https://github.com/young-developer/nppNavigateTo/releases/tag/v.2.0.2

**Comment by Skrell** [comment]
Still happens when I delete the entered phrase for search and keep hitting "delete" button
![image](https://user-images.githubusercontent.com/590266/204351693-cfe9c322-64aa-4455-8948-5247f5a68c8f.png)

Also upon opening the search, I'd except to see a list of all the files open in tabs before typing anything.  Perhaps you changed this behavior on purpose so that you ONLY see results upon entering a phrase to search for?

**Comment by young-developer** [comment]
Yes, it shows tabs, files, commands after typing. You can set typing limit in settings.

**Comment by young-developer** [comment]
@Skrell Please send me debug info too: 
![image](https://user-images.githubusercontent.com/4460168/204354653-76e45882-0141-455b-8d1c-74fdac01de88.png)

**Comment by young-developer** [comment]
also try to install version with toolset v142_xp

**Comment by Skrell** [comment]
> @Skrell Please send me debug info too: ![image](https://user-images.githubusercontent.com/4460168/204354653-76e45882-0141-455b-8d1c-74fdac01de88.png)

Notepad++ v8.4.7   (32-bit)
Build time : Nov  1 2022 - 23:29:20
Path : C:\Users\vbonaven\Programs\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.1766
Current ANSI codepage : 1252
Plugins : 
    BookmarksDook (3.1)
    BracketsCheck (1.2.2)
    CodeAlignmentNpp (14.1.107)
    Comment Wrap (1.0.0.5)
    ComparePlus (1)
    CSVLint (0.4.6.2)
    DSpellCheck (1.4.23)
    Explorer (1.8.2.18)
    HexEditor (0.9.12)
    LocationNavigate (0.4.8.1)
    LuaScript (0.12)
    MultiClipboard (2.1)
    NavigateTo (2)
    NppConverter (4.4)
    NppExport (0.4)
    PythonScript (1.5.4)

**Comment by Skrell** [comment]
> toolset v142_xp

What is this?

**Comment by Skrell** [comment]
Nevermind figure it out.  I tried the v142_xp version and still got this : 
![image](https://user-images.githubusercontent.com/590266/204363225-9b7cb79d-499e-4045-92f0-1d82e6d0da2b.png)

**Comment by young-developer** [comment]
@Skrell Please could you try to test on files by clicking ctrl+n and without other plugins? (is filepath for your file more than 260 chars?) have you tested on 64bit version?

**Comment by Skrell** [comment]
Ok finally getting somewhere, I removed all plugins and it still happened.  THEN I looked at all the file names and there was 1 with a path that was very long (maybe more than 256? not sure?) so I closed it, restarted Notepad++ and boom everything was fine.  Then I re-added ALL my plugins and restarted and boom STILL working.  So I think you need to add something for files that have very long paths; however, if notepad++ has NO ISSUE with those paths I'm not sure why your plugin does? 

Also can you please make it so the topmost search result is automatically highlighted so you can just press "enter" and switch to that tab?   

Right now I have to manually hit the down arrow to get the file I want to switch to and/or use the mouse click.  I was really hoping for your plugin to be a quick "search a few characters then quickly switch to that file" plugin.

**Comment by Skrell** [comment]
Also can you please automatically clear the last typed search when reopening the plugin window?  Currently I start typing at the END of the previous searched letters.

**Comment by young-developer** [comment]
@Skrell Check this version: https://github.com/young-developer/nppNavigateTo/releases/tag/v.2.1.1

**Comment by Skrell** [comment]
> @Skrell Check this version: https://github.com/young-developer/nppNavigateTo/releases/tag/v.2.1.1

Working great now!    Last thing!  Can you give an option to prefer filename over path when doing a search? So when I hit "enter" it goes to the correct file?  
![image](https://user-images.githubusercontent.com/590266/204379253-81e506d4-4d94-4209-a610-51fc024f91be.png)

**Comment by young-developer** [comment]
Some bug fixes and prefer filename search: https://github.com/young-developer/nppNavigateTo/releases/tag/v.2.2.1
@Skrell Please open new ticket for `fuzzy` search.
